INSERT INTO course (courseId, courseName, creadit) VALUES ('1', '职业发展与就业指导（上）', '1');
INSERT INTO course (courseId, courseName, creadit) VALUES ('2', '新生研讨与学科导论(Ⅰ)', '5');
INSERT INTO course (courseId, courseName, creadit) VALUES ('3', '班级指导', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('4', '西电校史', '4');
INSERT INTO course (courseId, courseName, creadit) VALUES ('5', 'Microwave Techniques/微波技术', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('6', 'High Frequency Circuit/高频电路', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('7', '电路分析基础', '4');
INSERT INTO course (courseId, courseName, creadit) VALUES ('8', '数字电路与逻辑设计', '4');
INSERT INTO course (courseId, courseName, creadit) VALUES ('9', '电子线路实验（Ⅰ）', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('10', '程序思维：让人脑像电脑那样思考', '1');
INSERT INTO course (courseId, courseName, creadit) VALUES ('11', '生产实习', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('12', '课程设计', '1');
INSERT INTO course (courseId, courseName, creadit) VALUES ('13', '电子系统设计实践', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('14', '毕业设计', '5');
INSERT INTO course (courseId, courseName, creadit) VALUES ('15', '信号处理与系统分析', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('16', '复变函数', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('17', '微处理器系统与应用', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('18', '高频电子线路', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('19', '随机信号分析', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('20', '通信原理', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('21', '数字信号处理', '1');
INSERT INTO course (courseId, courseName, creadit) VALUES ('22', '随机信号实验', '2');
INSERT INTO course (courseId, courseName, creadit) VALUES ('23', '通信原理实验', '3');
INSERT INTO course (courseId, courseName, creadit) VALUES ('24', '通信系统', '4');
INSERT INTO course (courseId, courseName, creadit) VALUES ('25', '射频通信电路', '4');
INSERT INTO course (courseId, courseName, creadit) VALUES ('26', '共识算法与机制', '4');
INSERT INTO course (courseId, courseName, creadit) VALUES ('27', '数据挖掘导论', '1');
