MYSTACK  SEGMENT PARA 'stack'
; DW	  100 DUP(?)
MYSTACK  ENDS


DATA  SEGMENT PARA 'data'
; DATA DEFINE
Sno DB 'ZhangJunhua! 16030199025',0AH,0DH,'$'
DATA  ENDS


CODE  SEGMENT PARA 'code'
MY_PROC    PROC	FAR	
ASSUME CS:CODE,DS:DATA,SS:MYSTACK
MAIN:   ;INSERT YOUR OWN CODES
.386	;386  Instruction Set

	MOV	AX,DATA
	MOV	DS,AX
	MOV	ES,AX
	MOV	AX,MYSTACK
	MOV	SS,AX
	MOV DX,OFFSET Sno
	INT 21H
	
MY_PROC     ENDp
CODE  ENDS
END MAIN